CREATE ROLE enter_ax_owner LOGIN PASSWORD 'enter_ax_owner' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE enter_ax_app LOGIN PASSWORD 'enter_ax_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;

ALTER DATABASE enter_ax_test OWNER TO enter_ax_owner;
ALTER SCHEMA public OWNER TO enter_ax_owner;
GRANT CONNECT ON DATABASE enter_ax_test TO enter_ax_app;
GRANT USAGE ON SCHEMA public TO enter_ax_app;
